######################################################################
# Automatically generated by qmake (2.01a) ?? 5? 18 14:12:39 2017
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Config.h Defpam.h em335x_drivers.h Gpio.h KEY.h Uartset.h
SOURCES += Gpio.cpp KEY.cpp main.cpp Uartset.cpp
